### ISSUE TITLE
Add Route Handlers for Root Path and Favicon to Resolve 404 Errors

### ISSUE THREAD

**Issue by allamiro** [abolkog/express-ts-starter#2]
Following the implementation of the repo i received a 404 error  messages. The 404 errors for the root path and /favicon.ico are typical if those routes are not defined, but this does not mean your application setup is incorrect. If desired, you can implement additional route handlers to handle these cases. They are just annoying. 

```
(base) allamiro@fedora:~/Downloads/Khalid-tests/express/express-ts-starter$ npm run dev

> express-ts-starter@1.0.0 dev
> NODE_ENV=development nodemon

[nodemon] 3.1.7
[nodemon] to restart at any time, enter rs
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting ts-node --files src/server.ts
[2024-11-03 22:30:41] info: Express app is running and listening on port 5000 
[2024-11-03 22:30:49] error: {
  "code": 404,
  "requestedUrl": "/",
  "message": "The requested resources was not found",
  "stack": "Error: The requested resources was not found\n    at App.initErrorHandlers (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:44:27)\n    at new App (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:21:10)\n    at Object.<anonymous> (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/server.ts:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1467:14)\n    at Module.m._compile (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1282:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1098:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)"
} 
[2024-11-03 22:30:49] error: {
  "code": 404,
  "requestedUrl": "/favicon.ico",
  "message": "The requested resources was not found",
  "stack": "Error: The requested resources was not found\n    at App.initErrorHandlers (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:44:27)\n    at new App (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:21:10)\n    at Object.<anonymous> (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/server.ts:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1467:14)\n    at Module.m._compile (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1282:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1098:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)"
} 
[2024-11-03 22:31:04] error: {
  "code": 404,
  "requestedUrl": "/favicon.ico",
  "message": "The requested resources was not found",
  "stack": "Error: The requested resources was not found\n    at App.initErrorHandlers (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:44:27)\n    at new App (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/app.ts:21:10)\n    at Object.<anonymous> (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/src/server.ts:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1467:14)\n    at Module.m._compile (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/allamiro/Downloads/Khalid-tests/express/express-ts-starter/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1282:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1098:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)"
}  

```

**Comment by abolkog** [comment]
Good point @allamiro , I did not think about consuming API from the browser, I have added a middleware to handle those and reduce the log noise
